# Configuration file for custom scenarios for `premise`
# Energy Perspective Scenario 2050+
# https://www.bfe.admin.ch/bfe/en/home/policy/energy-perspectives-2050-plus.html/

---

production pathways:
  DH woodchips:
    production volume:
      variable: production|district heat|Woodchips CHP
    ecoinvent alias:
      name: heat and power co-generation, wood chips, 6667 kW, state-of-the-art 2014
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True

  DH gas:
    production volume:
      variable: production|district heat|Gas CHP
    ecoinvent alias:
      name: heat and power co-generation, natural gas, combined cycle power plant, 400MW electrical
      reference product: heat, district or industrial, natural gas
      exists in original database: True

  DH waste:
    production volume:
      variable: production|district heat|Waste CHP
    ecoinvent alias:
      name: heat, from municipal waste incineration to generic market for heat district or industrial, other than natural gas
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True

  DH biomass:
    production volume:
      variable: production|district heat|Biomass
    ecoinvent alias:
      name: heat production, straw, at furnace 300kW
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True
      regionalize: True

  DH heatpumps:
    production volume:
      variable: production|district heat|heat pumps
    ecoinvent alias:
      name: heat from high temperature heat pump, 250 kw
      reference product: heat, district or industrial, other than natural gas
      exists in original database: False
      regionalize: True

  DH geothermal:
    production volume:
      variable: production|district heat|Geothermal
    ecoinvent alias:
      name: heat production, deep geothermal
      reference product: heat, deep geothermal
      exists in original database: True
      regionalize: True

  DH solarheat:
    production volume:
      variable: production|district heat|Solar heat
    ecoinvent alias:
      name: heat production, at 110 MW concentrating solar power plant, with thermal energy storage
      reference product: heat
      exists in original database: True
      regionalize: True

  DH residual industrial:
    production volume:
      variable: production|district heat|Residual industrial heat
    ecoinvent alias:
      name: excess industrial heat
      reference product: heat, district or industrial, other than natural gas
      exists in original database: False

  DH wood:
    production volume:
      variable: production|district heat|Wood boiler
    ecoinvent alias:
      name: heat production, softwood chips from forest, at furnace 5000kW, state-of-the-art 2014
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True
      regionalize: True

  DH straw:
    production volume:
      variable: production|district heat|Straw boiler
    ecoinvent alias:
      name: heat production, straw, at furnace 300kW
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True
      regionalize: True

  DH excess fuel factories:
    production volume:
      variable: production|district heat|Excess from fuels
    ecoinvent alias:
      name: excess industrial heat
      reference product: heat, district or industrial, other than natural gas
      exists in original database: False



  biomass chips:
    production volume:
      variable: production|individual heat|biomass furnace
    ecoinvent alias:
      name: heat production, softwood chips from forest, at furnace 50kW
      reference product: heat, central or small-scale, other than natural gas
      exists in original database: True
      regionalize: True

  biomass stove:
    production volume:
      variable: production|individual heat|biomass furnace
    ecoinvent alias:
      name: heat production, softwood chips from forest, at furnace 50kW
      reference product: heat, central or small-scale, other than natural gas
      exists in original database: True
      regionalize: True

  groundheat:
    production volume:
      variable: production|individual heat|ground heat pump
    ecoinvent alias:
      name: heat production, borehole heat exchanger, brine-water heat pump 10kW
      reference product: heat, brine-water heat pump 10kW
      exists in original database: True
      regionalize: True

  solar:
    production volume:
      variable: production|individual heat|solar heat
    ecoinvent alias:
      name: operation, solar collector system, Cu flat plate collector, one-family house, for hot water
      reference product: heat, central or small-scale, other than natural gas
      exists in original database: True
      regionalize: True

  heatpump:
    production volume:
      variable: production|individual heat|air heat pump
    ecoinvent alias:
      name: heat production, air-water heat pump 10kW
      reference product: heat, air-water heat pump 10kW
      exists in original database: True
      regionalize: True

  district heat:
    production volume:
      variable: consumption|district heat|District heat use
    ecoinvent alias:
      name: market for district heat, future
      reference product: district heat
      exists in original database: False
      new dataset: True

  individual heat:
    production volume:
      variable: consumption|individual heat|individual heat use
    ecoinvent alias:
      name: market for individual heat, future
      reference product: individual heat
      exists in original database: False
      new dataset: True

  individual heat, tiny house:
    production volume:
      variable: consumption|individual heat|individual heat use
    ecoinvent alias:
      name: market for individual heat, tiny house, future
      reference product: individual heat
      exists in original database: False
      new dataset: True

  electricity:
    production volume:
      variable: consumption|electricity|residential electricity use
    ecoinvent alias:
      name: market for electricity, low voltage
      reference product: electricity, low voltage
      exists in original database: True
      #new dataset: True
      ratio: 0.27778 #ratio to convert from kWh to MJ #conversion works correct

markets:
- name: market for district heat, future
  reference product: district heat
  unit: megajoule
  includes:
    - DH woodchips
    - DH gas
    - DH waste
    - DH biomass
    - DH heatpumps
    - DH geothermal
    - DH solarheat
    - DH residual industrial
    - DH wood
    - DH straw
    - DH excess fuel factories
  except regions:
    - World

  add: #add a flow of itself = loss
    - name: market for district heat, future
      reference product: district heat
      amount: 1.0 #scale this one with efficiency: technosphere: includes: -market for district heat, historical
  efficiency: #efficiency for loss
      - variable: lossess|district heat|distribution losses
        includes:
           technosphere:
              - name: market for district heat, future #efficiency only applied to this loss (input of itself)


- name: market for individual heat, future
  reference product: individual heat
  unit: megajoule
  includes:
    - biomass chips
    - groundheat
    - solar
    - heatpump
  except regions:
    - World

- name: market for individual heat, tiny house, future
  reference product: individual heat
  unit: megajoule
  includes:
    - biomass chips
    - groundheat
    - solar
    - heatpump
  except regions:
    - World

- name: market for residential energy, future
  reference product: residential energy
  unit: megajoule
  includes:
    - district heat
    - individual heat
    - electricity

  except regions:
    - World

- name: market for residential energy, tiny house, future
  reference product: residential energy
  unit: megajoule
  includes:
    - individual heat, tiny house
    - electricity

  except regions:
    - World