# Configuration file for custom scenarios for `premise`
# Energy Perspective Scenario 2050+
# https://www.bfe.admin.ch/bfe/en/home/policy/energy-perspectives-2050-plus.html/

---

production pathways:
  DH woodchips:
    production volume:
      variable: production|district heat|Woodchips CHP
    ecoinvent alias:
      name: heat and power co-generation, wood chips, 6667 kW, state-of-the-art 2014
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True

  DH gas:
    production volume:
      variable: production|district heat|Gas CHP
    ecoinvent alias:
      name: heat and power co-generation, natural gas, combined cycle power plant, 400MW electrical
      reference product: heat, district or industrial, natural gas
      exists in original database: True

  DH waste:
    production volume:
      variable: production|district heat|Waste CHP
    ecoinvent alias:
      name: heat, from municipal waste incineration to generic market for heat district or industrial, other than natural gas
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True

  DH biomass:
    production volume:
      variable: production|district heat|Biomass
    ecoinvent alias:
      name: heat production, straw, at furnace 300kW
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True
      regionalize: True

  DH heatpumps: #TODO find large-scale inventory in literature
    production volume:
      variable: production|district heat|heat pumps
    ecoinvent alias:
      name:
      reference product:
      exists in original database: False
      regionalize: True

  DH geothermal:
    production volume:
      variable: production|district heat|Geothermal
    ecoinvent alias:
      name: heat production, deep geothermal
      reference product: heat, deep geothermal
      exists in original database: True
      regionalize: True

  DH solarheat:
    production volume:
      variable: production|district heat|Solar heat
    ecoinvent alias:
      name: heat production, at 110 MW concentrating solar power plant, with thermal energy storage
      reference product: heat
      exists in original database: True
      regionalize: True

  DH residual industrial:
    production volume:
      variable: production|district heat|Residual industrial heat
    ecoinvent alias:
      name: excess industrial heat
      reference product: heat, district or industrial, other than natural gas
      exists in original database: False

  DH wood:
    production volume:
      variable: production|district heat|Wood boiler
    ecoinvent alias:
      name: heat production, softwood chips from forest, at furnace 5000kW, state-of-the-art 2014
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True
      regionalize: True

  DH straw:
    production volume:
      variable: production|district heat|Straw boiler
    ecoinvent alias:
      name: heat production, straw, at furnace 300kW
      reference product: heat, district or industrial, other than natural gas
      exists in original database: True
      regionalize: True

  DH excess fuel factories:
    production volume:
      variable: production|district heat|Excess from fuels
    ecoinvent alias:
      name: excess industrial heat
      reference product: heat, district or industrial, other than natural gas
      exists in original database: False



  district heat:
    production volume:
      variable:
    ecoinvent alias:
      name: market for district heat, future
      reference product: district heat
      exists in original database: False
      new dataset: True

markets:
- name: market for district heat, future
  reference product: district heat
  unit: megajoule
  includes:
    - DH woodchips
    - DH gas
    - DH waste
    - DH biomass
    - DH heatpumps
    - DH geothermal
    - DH solarheat
    - DH residual industrial
    - DH wood
    - DH straw
    - DH excess fuel factories
  except regions:
    - World

  add: #add a flow of itself = loss
    - name: market for district heat, future
      reference product: district heat
      amount: 1.0 #scale this one with efficiency: technosphere: includes: -market for district heat, historical
  efficiency: #efficiency for loss
      - variable: lossess|district heat|distribution losses
        includes:
           technosphere:
              - name: market for district heat, future #efficiency only applied to this loss (input of itself)
